cryptodashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dashboard.urls')),
    path('cryptos/', include('cryptos.urls')),
    path('watchlist/', include('watchlist.urls')),
    path('admin/', admin.site.urls),
]

cryptos/urls.py
from django.urls import path

from . import views

app_name = 'cryptos'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add-favorite/', views.add_favorite, name="add_favorite"),
    path('remove-from-watchlist/', views.remove_from_watchlist, name="remove_from_watchlist"),
    path('<slug:ticker>/', views.DetailView.as_view(), name="get_single_crypto"),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='dashboard_index')
]

watchlist/urls.py
from django.urls import path

from . import views

app_name = 'watchlist'
urlpatterns = [
    path('', views.render_favorites, name='index'),
    path('add-favorite/', views.add_favorite, name="add_favorite"),
    path('remove-favorite/<str:name>/', views.remove_favorite, name='remove_favorite')
]

coinmarketcap_api/models.py
from django.db import models

# Create your models here.

cryptos/models.py
from django.db import models

class Favorite(models.Model):
    ticker = models.CharField(max_length=5)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.ticker

    def fake_function(self, a, b):
        return a + b

watchlist/models.py
from django.db import models

class Favorite(models.Model):
    ticker = models.CharField(max_length=5)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.ticker

coinmarketcap_api/views.py
from django.shortcuts import render

# Create your views here.

cryptos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse
from django.views.generic import DetailView, ListView

from .models import Favorite

def remove_from_watchlist(request):
    name = request.GET['name']
    if name:
        thing = Favorite.objects.get(name=name)
        thing.delete()
    cryptos = Favorite.objects.all()
    context = {
        'cryptos': cryptos
    }
    return render(request, 'cryptos/index.html', context)

def add_favorite(request):
    ticker = request.POST['ticker']
    name = request.POST['name']
    if ticker and name:
        new_fav = Favorite(name=name, ticker=ticker)
        new_fav.save()

    cryptos = Favorite.objects.all()
    context = {
        'cryptos': cryptos
    }
    return render(request, 'cryptos/index.html', context)

class IndexView(ListView):
    template_name = 'cryptos/index.html'
    context_object_name = 'cryptos'

    def get_queryset(self):
        return Favorite.objects.all()

class DetailView(DetailView):
    template_name = 'cryptos/detail.html'
    context_object_name = 'crypto'

    def get_object(self):
        thing = get_object_or_404(Favorite, ticker__exact=self.kwargs['ticker'])
        return thing

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context = {}
    return render(request, 'dashboard/dashboard.html', context)

watchlist/views.py
from django.views.generic import ListView
from django.shortcuts import render

from coinmarketcap_api.api import Api

from .models import Favorite

class IndexView(ListView):
    template_name = 'watchlist/index.html'
    context_object_name = 'cryptos'

    def get_queryset(self):
        return Favorite.objects.all()

def render_favorites(request):
    tickers = Favorite.objects.all()
    ticker_list = list(tickers)
    ticker_list_string = ""
    

    tickers_list = [x.ticker for x in ticker_list]
    for x in tickers_list:
        ticker_list_string += str(x)
        ticker_list_string += ","
    ticker_list_string = ticker_list_string[:-1]

    api = Api()
    thing = api.getQuotes(ticker_list_string)
    dict = {}
    for x in thing:
        dict.update(x)

    cryptos = Favorite.objects.all()
    context = {
        'cryptos': cryptos,
        'thing': dict
    }
    return render(request, 'watchlist/index.html', context)

def add_favorite(request):
    ticker = request.POST['ticker']
    name = request.POST['name']
    if ticker and name:
        new_fav = Favorite(name=name, ticker=ticker)
        new_fav.save()

    return render_favorites(request)

def remove_favorite(request, name):
    if name:
        thing = Favorite.objects.get(name=name)
        thing.delete()
    return render_favorites(request)

cryptodashboard/templates/cryptodashboard/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'cryptodashboard/base.css' %}">
</head>

<body>
    {% include "navbar.html" %}
    
    {% block body %}
    {% endblock body %}

    {% block footer %}
    {% endblock footer %}
</body>

</html>

cryptodashboard/templates/cryptodashboard/navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'cryptodashboard/navbar.css' %}">

<div class="navbar">
    <div class="site_title_wrapper">
        <div class="dashboard_title">
            <a class="homepage_link" href="/">CryptoDashboard</a>
        </div>
    </div>


    <div class="navbar_links_wrapper">

        <div class="navbar_link_item">
            <a class="watchlist_button_wrapper" href="{% url 'watchlist:index' %}">
                <button type="button">Watchlist</button>
            </a>
        </div>   

        <div class="navbar_link_item">
            <a class="user_auth_button_wrapper" href="">
                <button type="button">Login</button>
            </a>
        </div>  

    </div>     

</div>

cryptodashboard/templates/shared/base.html
<!DOCTYPE html>
<html>
<head>
    {# {% load static %} #}
    {# <link rel="stylesheet" type="text/css" href="{% static 'cryptodashboard/shared/style.css' %}"> #}
</head>

<body>
    {% include "header.html" %}
    
    {% block body %}
    {% endblock body %}

    {% block footer %}
    {% endblock footer %}
</body>

</html>

cryptos/templates/cryptos/detail.html
{% extends 'base.html' %}


{% block body %}
<input type="button" value="Back" onClick="javascript:history.go(-1);">

<h1>{{ crypto.name }}</h1>

{% endblock body %}

cryptos/templates/cryptos/index.html
{% extends "base.html" %}
{% block body %}

<input type="button" value="Back" onClick="javascript:history.go(-1);">

{% if cryptos %}
    <ul>
    {% for crypto in cryptos %}
        <li>
            <a href="{% url 'cryptos:get_single_crypto' crypto.ticker %}">{{ crypto.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no cryptos yet!</p>
{% endif %}

<form action="{% url 'cryptos:add_favorite' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Add to favorites</h1></legend>
        <label for="ticker">Ticker</label>
        <input type="text" name="ticker">

        <label for="name">Name</label>
        <input type="text" name="name">
    </fieldset>
    <input type="submit" value="Add Favorite">
</form>

<form action="{% url 'cryptos:remove_from_watchlist' %}" method="delete">
    <fieldset>
        <legend><h1>Remove from favorites</h1></legend>
        <label for="name">Name</label>
        <input type="text" name="name">
    </fieldset>
    <input type="submit" value="Remove Favorite">
</form>

{% endblock body %}

dashboard/templates/dashboard/dashboard.html
{% extends "base.html" %}


{% block body %}
<a href="{% url 'cryptos:index' %}">
    <button type="button">Cryptos</button>
</a>
{% endblock body %}

watchlist/templates/watchlist/index.html
{% extends "base.html" %}
{% block body %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'watchlist/index.css' %}">

<form action="{% url 'watchlist:add_favorite' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Add to favorites</h1></legend>
        <label for="ticker">Ticker</label>
        <input type="text" name="ticker">

        <label for="name">Name</label>
        <input type="text" name="name">
    </fieldset>
    <input type="submit" value="Add Favorite">
</form>

<div class="favorites_list_wrapper">
    {% if cryptos %}
        {% for crypto in cryptos %}
            <div class="thing_djs">
            {% include 'watchlist/watchlist_line_item.html' %}
            </div>
        {% endfor %}
    {% else %}
        <p>There are no cryptos yet!</p>
    {% endif %}
    
</div>

{% endblock body %}

watchlist/templates/watchlist/watchlist_line_item.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'watchlist/watchlist_line_item.css' %}">

{% load watchlist_extras %}

<div class="watchlist_line_item_wrapper">
    <div class="watchlist_line_item crypto_name">
        <a href="{% url 'cryptos:get_single_crypto' crypto.ticker %}">{{ crypto.name }}</a>
    </div>
    
    <div class="watchlist_line_item">
        <p>{{ thing | format_like_currency:crypto.ticker }}</p>
    </div>

    <div class="watchlist_line_item">
        <button class="delete_button" onclick="location.href='{% url 'watchlist:remove_favorite' crypto.name %}'">X</button>
    </div>
</div>